// Code generated by goctl. DO NOT EDIT.
// Source: goods.proto

package server

import (
	"context"

	"zero-shop/app/goods/rpc/internal/logic"
	"zero-shop/app/goods/rpc/internal/svc"
	"zero-shop/app/goods/rpc/pb"
)

type GoodsServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedGoodsServer
}

func NewGoodsServer(svcCtx *svc.ServiceContext) *GoodsServer {
	return &GoodsServer{
		svcCtx: svcCtx,
	}
}

func (s *GoodsServer) List(ctx context.Context, in *pb.ListRequest) (*pb.ListResponse, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *GoodsServer) Detail(ctx context.Context, in *pb.DetailRequest) (*pb.GoodsInfoResponse, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
