// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Username string `json:"username"`
	Password string `json:"password"`
}

type LoginRsp struct {
	Token string `json:"token"`
}

type UserDetailReq struct {
}

type UserDetailRsq struct {
	ID       int64  `json:"id"`
	UserName string `json:"username"`
}
