// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v3.19.4
// source: app/pay/rpc/pay.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PayReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn string `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
	UserId  int64  `protobuf:"varint,2,opt,name=UserId,proto3" json:"UserId,omitempty"`
}

func (x *PayReq) Reset() {
	*x = PayReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pay_rpc_pay_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayReq) ProtoMessage() {}

func (x *PayReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_pay_rpc_pay_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayReq.ProtoReflect.Descriptor instead.
func (*PayReq) Descriptor() ([]byte, []int) {
	return file_app_pay_rpc_pay_proto_rawDescGZIP(), []int{0}
}

func (x *PayReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *PayReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type PayResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *PayResp) Reset() {
	*x = PayResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pay_rpc_pay_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PayResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PayResp) ProtoMessage() {}

func (x *PayResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_pay_rpc_pay_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PayResp.ProtoReflect.Descriptor instead.
func (*PayResp) Descriptor() ([]byte, []int) {
	return file_app_pay_rpc_pay_proto_rawDescGZIP(), []int{1}
}

func (x *PayResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ThirdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *ThirdReq) Reset() {
	*x = ThirdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pay_rpc_pay_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdReq) ProtoMessage() {}

func (x *ThirdReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_pay_rpc_pay_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdReq.ProtoReflect.Descriptor instead.
func (*ThirdReq) Descriptor() ([]byte, []int) {
	return file_app_pay_rpc_pay_proto_rawDescGZIP(), []int{2}
}

func (x *ThirdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type ThirdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id             int64   `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CreateTime     int64   `protobuf:"varint,2,opt,name=CreateTime,proto3" json:"CreateTime,omitempty"`
	UserId         int64   `protobuf:"varint,3,opt,name=UserId,proto3" json:"UserId,omitempty"`
	PayMode        int64   `protobuf:"varint,4,opt,name=PayMode,proto3" json:"PayMode,omitempty"` // 1 微信支付 2 支付宝支付
	PayStatus      int64   `protobuf:"varint,5,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`
	PayTime        int64   `protobuf:"varint,6,opt,name=PayTime,proto3" json:"PayTime,omitempty"`
	TradeType      string  `protobuf:"bytes,7,opt,name=TradeType,proto3" json:"TradeType,omitempty"`
	TradeState     string  `protobuf:"bytes,8,opt,name=TradeState,proto3" json:"TradeState,omitempty"`
	PayTotal       float64 `protobuf:"fixed64,9,opt,name=PayTotal,proto3" json:"PayTotal,omitempty"`
	TransactionId  string  `protobuf:"bytes,10,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`
	TradeStateDesc string  `protobuf:"bytes,11,opt,name=TradeStateDesc,proto3" json:"TradeStateDesc,omitempty"`
	OrderSn        string  `protobuf:"bytes,12,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
}

func (x *ThirdResp) Reset() {
	*x = ThirdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pay_rpc_pay_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ThirdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThirdResp) ProtoMessage() {}

func (x *ThirdResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_pay_rpc_pay_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThirdResp.ProtoReflect.Descriptor instead.
func (*ThirdResp) Descriptor() ([]byte, []int) {
	return file_app_pay_rpc_pay_proto_rawDescGZIP(), []int{3}
}

func (x *ThirdResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ThirdResp) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

func (x *ThirdResp) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ThirdResp) GetPayMode() int64 {
	if x != nil {
		return x.PayMode
	}
	return 0
}

func (x *ThirdResp) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *ThirdResp) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

func (x *ThirdResp) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *ThirdResp) GetTradeState() string {
	if x != nil {
		return x.TradeState
	}
	return ""
}

func (x *ThirdResp) GetPayTotal() float64 {
	if x != nil {
		return x.PayTotal
	}
	return 0
}

func (x *ThirdResp) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *ThirdResp) GetTradeStateDesc() string {
	if x != nil {
		return x.TradeStateDesc
	}
	return ""
}

func (x *ThirdResp) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type GetThirdByOrderSnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OrderSn string `protobuf:"bytes,1,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`
}

func (x *GetThirdByOrderSnReq) Reset() {
	*x = GetThirdByOrderSnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pay_rpc_pay_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetThirdByOrderSnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetThirdByOrderSnReq) ProtoMessage() {}

func (x *GetThirdByOrderSnReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_pay_rpc_pay_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetThirdByOrderSnReq.ProtoReflect.Descriptor instead.
func (*GetThirdByOrderSnReq) Descriptor() ([]byte, []int) {
	return file_app_pay_rpc_pay_proto_rawDescGZIP(), []int{4}
}

func (x *GetThirdByOrderSnReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type UpdateByOrderSnReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Sn             string  `protobuf:"bytes,1,opt,name=Sn,proto3" json:"Sn,omitempty"` // 订单流水号
	UpdateTime     int64   `protobuf:"varint,2,opt,name=UpdateTime,proto3" json:"UpdateTime,omitempty"`
	PayMode        int64   `protobuf:"varint,3,opt,name=PayMode,proto3" json:"PayMode,omitempty"`              // 1 微信支付 2 支付宝支付
	TradeType      string  `protobuf:"bytes,4,opt,name=TradeType,proto3" json:"TradeType,omitempty"`           // 支付类型
	TradeState     string  `protobuf:"bytes,5,opt,name=TradeState,proto3" json:"TradeState,omitempty"`         // 交易状态
	PayTotal       float64 `protobuf:"fixed64,6,opt,name=PayTotal,proto3" json:"PayTotal,omitempty"`           // 支付金额
	TransactionId  string  `protobuf:"bytes,7,opt,name=TransactionId,proto3" json:"TransactionId,omitempty"`   // 微信的订单号
	TradeStateDesc string  `protobuf:"bytes,8,opt,name=TradeStateDesc,proto3" json:"TradeStateDesc,omitempty"` // 订单支付描述
	OrderSn        string  `protobuf:"bytes,9,opt,name=OrderSn,proto3" json:"OrderSn,omitempty"`               // 订单sn
	PayStatus      int64   `protobuf:"varint,10,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`         // -1:支付失败 0:未支付 1:支付成功 2:已退款
	PayTime        int64   `protobuf:"varint,11,opt,name=PayTime,proto3" json:"PayTime,omitempty"`             // 支付时间
}

func (x *UpdateByOrderSnReq) Reset() {
	*x = UpdateByOrderSnReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pay_rpc_pay_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateByOrderSnReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateByOrderSnReq) ProtoMessage() {}

func (x *UpdateByOrderSnReq) ProtoReflect() protoreflect.Message {
	mi := &file_app_pay_rpc_pay_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateByOrderSnReq.ProtoReflect.Descriptor instead.
func (*UpdateByOrderSnReq) Descriptor() ([]byte, []int) {
	return file_app_pay_rpc_pay_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateByOrderSnReq) GetSn() string {
	if x != nil {
		return x.Sn
	}
	return ""
}

func (x *UpdateByOrderSnReq) GetUpdateTime() int64 {
	if x != nil {
		return x.UpdateTime
	}
	return 0
}

func (x *UpdateByOrderSnReq) GetPayMode() int64 {
	if x != nil {
		return x.PayMode
	}
	return 0
}

func (x *UpdateByOrderSnReq) GetTradeType() string {
	if x != nil {
		return x.TradeType
	}
	return ""
}

func (x *UpdateByOrderSnReq) GetTradeState() string {
	if x != nil {
		return x.TradeState
	}
	return ""
}

func (x *UpdateByOrderSnReq) GetPayTotal() float64 {
	if x != nil {
		return x.PayTotal
	}
	return 0
}

func (x *UpdateByOrderSnReq) GetTransactionId() string {
	if x != nil {
		return x.TransactionId
	}
	return ""
}

func (x *UpdateByOrderSnReq) GetTradeStateDesc() string {
	if x != nil {
		return x.TradeStateDesc
	}
	return ""
}

func (x *UpdateByOrderSnReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UpdateByOrderSnReq) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *UpdateByOrderSnReq) GetPayTime() int64 {
	if x != nil {
		return x.PayTime
	}
	return 0
}

type UpdateByOrderSnResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
}

func (x *UpdateByOrderSnResp) Reset() {
	*x = UpdateByOrderSnResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_app_pay_rpc_pay_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateByOrderSnResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateByOrderSnResp) ProtoMessage() {}

func (x *UpdateByOrderSnResp) ProtoReflect() protoreflect.Message {
	mi := &file_app_pay_rpc_pay_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateByOrderSnResp.ProtoReflect.Descriptor instead.
func (*UpdateByOrderSnResp) Descriptor() ([]byte, []int) {
	return file_app_pay_rpc_pay_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateByOrderSnResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_app_pay_rpc_pay_proto protoreflect.FileDescriptor

var file_app_pay_rpc_pay_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x70, 0x70, 0x2f, 0x70, 0x61, 0x79, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x61,
	0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70, 0x62, 0x22, 0x3a, 0x0a, 0x06, 0x50,
	0x61, 0x79, 0x52, 0x65, 0x71, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x19, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x49, 0x64, 0x22, 0x1a, 0x0a, 0x08, 0x54, 0x68, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e,
	0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x22, 0xe7,
	0x02, 0x0a, 0x09, 0x54, 0x68, 0x69, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x0a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x55, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1c,
	0x0a, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07,
	0x50, 0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50,
	0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54, 0x72, 0x61, 0x64, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x54, 0x72, 0x61, 0x64, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x50, 0x61, 0x79, 0x54, 0x6f, 0x74, 0x61, 0x6c,
	0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49,
	0x64, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53,
	0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x63, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0e,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x63, 0x12, 0x18,
	0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x22, 0x30, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x54,
	0x68, 0x69, 0x72, 0x64, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x52, 0x65, 0x71,
	0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x22, 0xd8, 0x02, 0x0a, 0x12, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x52, 0x65,
	0x71, 0x12, 0x0e, 0x0a, 0x02, 0x53, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x53,
	0x6e, 0x12, 0x1e, 0x0a, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x69, 0x6d,
	0x65, 0x12, 0x18, 0x0a, 0x07, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x50, 0x61, 0x79, 0x4d, 0x6f, 0x64, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x54, 0x72, 0x61, 0x64, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x54, 0x72, 0x61,
	0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x79,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x01, 0x52, 0x08, 0x50, 0x61, 0x79,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x12, 0x24, 0x0a, 0x0d, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x12, 0x26, 0x0a, 0x0e, 0x54,
	0x72, 0x61, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44, 0x65, 0x73, 0x63, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0e, 0x54, 0x72, 0x61, 0x64, 0x65, 0x53, 0x74, 0x61, 0x74, 0x65, 0x44,
	0x65, 0x73, 0x63, 0x12, 0x18, 0x0a, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x1c, 0x0a,
	0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x50, 0x61, 0x79, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x50,
	0x61, 0x79, 0x54, 0x69, 0x6d, 0x65, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x50, 0x61,
	0x79, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x25, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42,
	0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02,
	0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64, 0x32, 0xd0, 0x01, 0x0a,
	0x03, 0x70, 0x61, 0x79, 0x12, 0x21, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x0a,
	0x2e, 0x70, 0x62, 0x2e, 0x50, 0x61, 0x79, 0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x70, 0x62, 0x2e,
	0x50, 0x61, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x24, 0x0a, 0x05, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x12, 0x0c, 0x2e, 0x70, 0x62, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0d,
	0x2e, 0x70, 0x62, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3c, 0x0a,
	0x11, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x72, 0x64, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72,
	0x53, 0x6e, 0x12, 0x18, 0x2e, 0x70, 0x62, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x68, 0x69, 0x72, 0x64,
	0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x0d, 0x2e, 0x70,
	0x62, 0x2e, 0x54, 0x68, 0x69, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x42, 0x0a, 0x0f, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x12, 0x16,
	0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65,
	0x72, 0x53, 0x6e, 0x52, 0x65, 0x71, 0x1a, 0x17, 0x2e, 0x70, 0x62, 0x2e, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x42, 0x79, 0x4f, 0x72, 0x64, 0x65, 0x72, 0x53, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x42,
	0x06, 0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_app_pay_rpc_pay_proto_rawDescOnce sync.Once
	file_app_pay_rpc_pay_proto_rawDescData = file_app_pay_rpc_pay_proto_rawDesc
)

func file_app_pay_rpc_pay_proto_rawDescGZIP() []byte {
	file_app_pay_rpc_pay_proto_rawDescOnce.Do(func() {
		file_app_pay_rpc_pay_proto_rawDescData = protoimpl.X.CompressGZIP(file_app_pay_rpc_pay_proto_rawDescData)
	})
	return file_app_pay_rpc_pay_proto_rawDescData
}

var file_app_pay_rpc_pay_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_app_pay_rpc_pay_proto_goTypes = []interface{}{
	(*PayReq)(nil),               // 0: pb.PayReq
	(*PayResp)(nil),              // 1: pb.PayResp
	(*ThirdReq)(nil),             // 2: pb.ThirdReq
	(*ThirdResp)(nil),            // 3: pb.ThirdResp
	(*GetThirdByOrderSnReq)(nil), // 4: pb.GetThirdByOrderSnReq
	(*UpdateByOrderSnReq)(nil),   // 5: pb.UpdateByOrderSnReq
	(*UpdateByOrderSnResp)(nil),  // 6: pb.UpdateByOrderSnResp
}
var file_app_pay_rpc_pay_proto_depIdxs = []int32{
	0, // 0: pb.pay.Create:input_type -> pb.PayReq
	2, // 1: pb.pay.Third:input_type -> pb.ThirdReq
	4, // 2: pb.pay.GetThirdByOrderSn:input_type -> pb.GetThirdByOrderSnReq
	5, // 3: pb.pay.UpdateByOrderSn:input_type -> pb.UpdateByOrderSnReq
	1, // 4: pb.pay.Create:output_type -> pb.PayResp
	3, // 5: pb.pay.Third:output_type -> pb.ThirdResp
	3, // 6: pb.pay.GetThirdByOrderSn:output_type -> pb.ThirdResp
	6, // 7: pb.pay.UpdateByOrderSn:output_type -> pb.UpdateByOrderSnResp
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_app_pay_rpc_pay_proto_init() }
func file_app_pay_rpc_pay_proto_init() {
	if File_app_pay_rpc_pay_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_app_pay_rpc_pay_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pay_rpc_pay_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PayResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pay_rpc_pay_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pay_rpc_pay_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ThirdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pay_rpc_pay_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetThirdByOrderSnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pay_rpc_pay_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateByOrderSnReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_app_pay_rpc_pay_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateByOrderSnResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_app_pay_rpc_pay_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_app_pay_rpc_pay_proto_goTypes,
		DependencyIndexes: file_app_pay_rpc_pay_proto_depIdxs,
		MessageInfos:      file_app_pay_rpc_pay_proto_msgTypes,
	}.Build()
	File_app_pay_rpc_pay_proto = out.File
	file_app_pay_rpc_pay_proto_rawDesc = nil
	file_app_pay_rpc_pay_proto_goTypes = nil
	file_app_pay_rpc_pay_proto_depIdxs = nil
}
