// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.19.4
// source: app/pay/rpc/pay.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Pay_Create_FullMethodName            = "/pb.pay/Create"
	Pay_Third_FullMethodName             = "/pb.pay/Third"
	Pay_GetThirdByOrderSn_FullMethodName = "/pb.pay/GetThirdByOrderSn"
	Pay_UpdateByOrderSn_FullMethodName   = "/pb.pay/UpdateByOrderSn"
)

// PayClient is the client API for Pay service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PayClient interface {
	Create(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error)
	Third(ctx context.Context, in *ThirdReq, opts ...grpc.CallOption) (*ThirdResp, error)
	GetThirdByOrderSn(ctx context.Context, in *GetThirdByOrderSnReq, opts ...grpc.CallOption) (*ThirdResp, error)
	UpdateByOrderSn(ctx context.Context, in *UpdateByOrderSnReq, opts ...grpc.CallOption) (*UpdateByOrderSnResp, error)
}

type payClient struct {
	cc grpc.ClientConnInterface
}

func NewPayClient(cc grpc.ClientConnInterface) PayClient {
	return &payClient{cc}
}

func (c *payClient) Create(ctx context.Context, in *PayReq, opts ...grpc.CallOption) (*PayResp, error) {
	out := new(PayResp)
	err := c.cc.Invoke(ctx, Pay_Create_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payClient) Third(ctx context.Context, in *ThirdReq, opts ...grpc.CallOption) (*ThirdResp, error) {
	out := new(ThirdResp)
	err := c.cc.Invoke(ctx, Pay_Third_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payClient) GetThirdByOrderSn(ctx context.Context, in *GetThirdByOrderSnReq, opts ...grpc.CallOption) (*ThirdResp, error) {
	out := new(ThirdResp)
	err := c.cc.Invoke(ctx, Pay_GetThirdByOrderSn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *payClient) UpdateByOrderSn(ctx context.Context, in *UpdateByOrderSnReq, opts ...grpc.CallOption) (*UpdateByOrderSnResp, error) {
	out := new(UpdateByOrderSnResp)
	err := c.cc.Invoke(ctx, Pay_UpdateByOrderSn_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PayServer is the server API for Pay service.
// All implementations must embed UnimplementedPayServer
// for forward compatibility
type PayServer interface {
	Create(context.Context, *PayReq) (*PayResp, error)
	Third(context.Context, *ThirdReq) (*ThirdResp, error)
	GetThirdByOrderSn(context.Context, *GetThirdByOrderSnReq) (*ThirdResp, error)
	UpdateByOrderSn(context.Context, *UpdateByOrderSnReq) (*UpdateByOrderSnResp, error)
	mustEmbedUnimplementedPayServer()
}

// UnimplementedPayServer must be embedded to have forward compatible implementations.
type UnimplementedPayServer struct {
}

func (UnimplementedPayServer) Create(context.Context, *PayReq) (*PayResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedPayServer) Third(context.Context, *ThirdReq) (*ThirdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Third not implemented")
}
func (UnimplementedPayServer) GetThirdByOrderSn(context.Context, *GetThirdByOrderSnReq) (*ThirdResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThirdByOrderSn not implemented")
}
func (UnimplementedPayServer) UpdateByOrderSn(context.Context, *UpdateByOrderSnReq) (*UpdateByOrderSnResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateByOrderSn not implemented")
}
func (UnimplementedPayServer) mustEmbedUnimplementedPayServer() {}

// UnsafePayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PayServer will
// result in compilation errors.
type UnsafePayServer interface {
	mustEmbedUnimplementedPayServer()
}

func RegisterPayServer(s grpc.ServiceRegistrar, srv PayServer) {
	s.RegisterService(&Pay_ServiceDesc, srv)
}

func _Pay_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PayReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pay_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).Create(ctx, req.(*PayReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay_Third_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ThirdReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).Third(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pay_Third_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).Third(ctx, req.(*ThirdReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay_GetThirdByOrderSn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetThirdByOrderSnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).GetThirdByOrderSn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pay_GetThirdByOrderSn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).GetThirdByOrderSn(ctx, req.(*GetThirdByOrderSnReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Pay_UpdateByOrderSn_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateByOrderSnReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PayServer).UpdateByOrderSn(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Pay_UpdateByOrderSn_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PayServer).UpdateByOrderSn(ctx, req.(*UpdateByOrderSnReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Pay_ServiceDesc is the grpc.ServiceDesc for Pay service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Pay_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.pay",
	HandlerType: (*PayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Pay_Create_Handler,
		},
		{
			MethodName: "Third",
			Handler:    _Pay_Third_Handler,
		},
		{
			MethodName: "GetThirdByOrderSn",
			Handler:    _Pay_GetThirdByOrderSn_Handler,
		},
		{
			MethodName: "UpdateByOrderSn",
			Handler:    _Pay_UpdateByOrderSn_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "app/pay/rpc/pay.proto",
}
