// Code generated by goctl. DO NOT EDIT.
// Source: order.proto

package server

import (
	"context"

	"zero-shop/app/order/rpc/internal/logic"
	"zero-shop/app/order/rpc/internal/svc"
	"zero-shop/app/order/rpc/pb"
)

type OrderServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedOrderServer
}

func NewOrderServer(svcCtx *svc.ServiceContext) *OrderServer {
	return &OrderServer{
		svcCtx: svcCtx,
	}
}

func (s *OrderServer) Create(ctx context.Context, in *pb.CreateOrderReq) (*pb.CreateOrderResp, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *OrderServer) List(ctx context.Context, in *pb.ListReq) (*pb.ListResp, error) {
	l := logic.NewListLogic(ctx, s.svcCtx)
	return l.List(in)
}

func (s *OrderServer) Detail(ctx context.Context, in *pb.DetailReq) (*pb.OrderInfoResp, error) {
	l := logic.NewDetailLogic(ctx, s.svcCtx)
	return l.Detail(in)
}
